#### Installing Pandas

In [1]:
%pip install pandas

Requirement already satisfied: pandas in /home/prajwalmac/anaconda3/envs/ds_venv/lib/python3.13/site-packages (2.3.3)
Requirement already satisfied: numpy>=1.26.0 in /home/prajwalmac/anaconda3/envs/ds_venv/lib/python3.13/site-packages (from pandas) (2.3.5)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/prajwalmac/anaconda3/envs/ds_venv/lib/python3.13/site-packages (from pandas) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in /home/prajwalmac/anaconda3/envs/ds_venv/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: tzdata>=2022.7 in /home/prajwalmac/anaconda3/envs/ds_venv/lib/python3.13/site-packages (from pandas) (2025.2)
Requirement already satisfied: six>=1.5 in /home/prajwalmac/anaconda3/envs/ds_venv/lib/python3.13/site-packages (from python-dateutil>=2.8.2->pandas) (1.17.0)
Note: you may need to restart the kernel to use updated packages.

#### Importing Pandas

In [3]:
import pandas as pd

#checking python version
pd.__version__

'2.3.3'

#### Creating a series

In [5]:
data = [100,200,300]

series = pd.Series(data) #Series() is more of constructor than a function

series

0    100
1    200
2    300
dtype: int64

#### Creating a dataframe

In [8]:
data_1 = [61,598,4,8]

df = pd.DataFrame(data_1)

df

     0
0   61
1  598
2    4
3    8

#### Naming the columns

In [12]:
data_1 = [61,598,4,8]

df = pd.DataFrame(data_1,columns=["Col_1"])

df

   Col_1
0     61
1    598
2      4
3      8

In [13]:
print(type(df))

<class 'pandas.core.frame.DataFrame'>

#### Creating dataframe from dictionary

In [16]:
dict_data = {
    "Name":["Prajwal","Suvam","Alice","Bob"],
    "Age":[21,24,26,29],
    "Salary":[5000,5000,2953,3941],
    "Department":["IT","HR","Sales","Marketing"]
}

df = pd.DataFrame(dict_data)

df

      Name  Age  Salary Department
0  Prajwal   21    5000         IT
1    Suvam   24    5000         HR
2    Alice   26    2953      Sales
3      Bob   29    3941  Marketing

#### Some basic functions

**1. head() function**
- returns the first/top rows
- default is 5 but can be changed

In [18]:
df.head(2)

      Name  Age  Salary Department
0  Prajwal   21    5000         IT
1    Suvam   24    5000         HR

**2. tail() function**
- returns the last/bottom rows
- default is 5 but can be changed

In [19]:
df.tail(2)

    Name  Age  Salary Department
2  Alice   26    2953      Sales
3    Bob   29    3941  Marketing

**3. shape function**
- returns the size of dataframe ie.(row_num,col_num)

In [21]:
df.shape

(4, 4)

**4.rename() function**
- renames the columns names
- column names must be provided as a key value pair

In [24]:
df1 = df.rename(columns={"Salary":"Monthly_Salary"})
df1

      Name  Age  Monthly_Salary Department
0  Prajwal   21            5000         IT
1    Suvam   24            5000         HR
2    Alice   26            2953      Sales
3      Bob   29            3941  Marketing

- if we want the change to be applied in the original/ the dataframe we are working on we can set inplace=True

In [26]:
df.rename(columns={"Salary":"Monthly_Salary"},inplace = True)
df

      Name  Age  Monthly_Salary Department
0  Prajwal   21            5000         IT
1    Suvam   24            5000         HR
2    Alice   26            2953      Sales
3      Bob   29            3941  Marketing

**4.info() function**
- gives info of the dataframe at basic level

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 4 entries, 0 to 3
Data columns (total 4 columns):
 #   Column          Non-Null Count  Dtype
---  ------          --------------  -----
 0   Name            4 non-null      object
 1   Age             4 non-null      int64
 2   Monthly_Salary  4 non-null      int64
 3   Department      4 non-null      object
dtypes: int64(2), object(2)
memory usage: 260.0+ bytes

**5.describe() function**
- provides statistical summary of numerical datas present in dataframe

In [28]:
df.describe()

             Age  Monthly_Salary
count   4.000000        4.000000
mean   25.000000     4223.500000
std     3.366502      983.171908
min    21.000000     2953.000000
25%    23.250000     3694.000000
50%    25.000000     4470.500000
75%    26.750000     5000.000000
max    29.000000     5000.000000