In [1]:
import pandas as pd

#### CSV Files Operation

In [2]:
data = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8],
    "Name": ["Ram", "Sita", "Gita", "Hari", "Nita", "Aman", "Rita", "Kiran"],
    "Age": [21, 22, 20, 23, 21, 24, 22, 23],
    "Gender": ["M", "F", "F", "M", "F", "M", "F", "M"],
    "Marks_Math": [78, 85, 69, 90, 74, 88, 81, 76],
    "Marks_Science": [82, 88, 72, 91, 79, 87, 84, 80],
    "Marks_English": [75, 80, 70, 85, 73, 82, 78, 77],
    "Result": ["Pass", "Pass", "Pass", "Pass", "Pass", "Pass", "Pass", "Pass"]
}

df = pd.DataFrame(data)
df

   ID   Name  Age Gender  Marks_Math  Marks_Science  Marks_English Result
0   1    Ram   21      M          78             82             75   Pass
1   2   Sita   22      F          85             88             80   Pass
2   3   Gita   20      F          69             72             70   Pass
3   4   Hari   23      M          90             91             85   Pass
4   5   Nita   21      F          74             79             73   Pass
5   6   Aman   24      M          88             87             82   Pass
6   7   Rita   22      F          81             84             78   Pass
7   8  Kiran   23      M          76             80             77   Pass

## Handling CSV Files

#### Saving file as csv

In [3]:
file_path = '/home/prajwalmac/data_science_self/pandas_self/data/sample_data.csv'

# at default index also gets saved but if we dont want to sace index we can add index=False
df.to_csv(file_path,index=False)

#### Loading CSV file

In [4]:
file_path = '/home/prajwalmac/data_science_self/pandas_self/data/sample_data.csv'

load_csv = pd.read_csv(file_path)

load_csv

   ID   Name  Age Gender  Marks_Math  Marks_Science  Marks_English Result
0   1    Ram   21      M          78             82             75   Pass
1   2   Sita   22      F          85             88             80   Pass
2   3   Gita   20      F          69             72             70   Pass
3   4   Hari   23      M          90             91             85   Pass
4   5   Nita   21      F          74             79             73   Pass
5   6   Aman   24      M          88             87             82   Pass
6   7   Rita   22      F          81             84             78   Pass
7   8  Kiran   23      M          76             80             77   Pass

## Handling Excel files

In [5]:
data = {
    "ID": [1, 2, 3, 4, 5, 6, 7, 8],
    "Name": ["Ram", "Sita", "Gita", "Hari", "Nita", "Aman", "Rita", "Kiran"],
    "Age": [21, 22, 20, 23, 21, 24, 22, 23],
    "Gender": ["M", "F", "F", "M", "F", "M", "F", "M"],
    "Marks_Math": [78, 85, 69, 90, 74, 88, 81, 76],
    "Marks_Science": [82, 88, 72, 91, 79, 87, 84, 80],
    "Marks_English": [75, 80, 70, 85, 73, 82, 78, 77],
    "Result": ["Pass", "Pass", "Pass", "Pass", "Pass", "Pass", "Pass", "Pass"]
}

df = pd.DataFrame(data)

df

   ID   Name  Age Gender  Marks_Math  Marks_Science  Marks_English Result
0   1    Ram   21      M          78             82             75   Pass
1   2   Sita   22      F          85             88             80   Pass
2   3   Gita   20      F          69             72             70   Pass
3   4   Hari   23      M          90             91             85   Pass
4   5   Nita   21      F          74             79             73   Pass
5   6   Aman   24      M          88             87             82   Pass
6   7   Rita   22      F          81             84             78   Pass
7   8  Kiran   23      M          76             80             77   Pass

#### Saving file as excel

In [6]:
%pip install openpyxl

Requirement already satisfied: openpyxl in /home/prajwalmac/anaconda3/envs/ds_venv/lib/python3.13/site-packages (3.1.5)
Requirement already satisfied: et-xmlfile in /home/prajwalmac/anaconda3/envs/ds_venv/lib/python3.13/site-packages (from openpyxl) (2.0.0)
Note: you may need to restart the kernel to use updated packages.

In [8]:
filepath = '/home/prajwalmac/data_science_self/pandas_self/data/sample_excel_data.xlsx'

df.to_excel(filepath,index=False)

#### Loading excel files

In [11]:
filepath = '/home/prajwalmac/data_science_self/pandas_self/data/sample_excel_data.xlsx'

load_excel = pd.read_excel(filepath)

load_csv

   ID   Name  Age Gender  Marks_Math  Marks_Science  Marks_English Result
0   1    Ram   21      M          78             82             75   Pass
1   2   Sita   22      F          85             88             80   Pass
2   3   Gita   20      F          69             72             70   Pass
3   4   Hari   23      M          90             91             85   Pass
4   5   Nita   21      F          74             79             73   Pass
5   6   Aman   24      M          88             87             82   Pass
6   7   Rita   22      F          81             84             78   Pass
7   8  Kiran   23      M          76             80             77   Pass

## Handling JSON files

#### Saving file as JSON

In [22]:
json_file_path =  '/home/prajwalmac/data_science_self/pandas_self/data/sample_json_data.json'

df.to_json(json_file_path,index=False)

#### Loading JSON File

In [23]:
json_file_path =  '/home/prajwalmac/data_science_self/pandas_self/data/sample_json_data.json'

pd.read_json(json_file_path)

   ID   Name  Age Gender  Marks_Math  Marks_Science  Marks_English Result
0   1    Ram   21      M          78             82             75   Pass
1   2   Sita   22      F          85             88             80   Pass
2   3   Gita   20      F          69             72             70   Pass
3   4   Hari   23      M          90             91             85   Pass
4   5   Nita   21      F          74             79             73   Pass
5   6   Aman   24      M          88             87             82   Pass
6   7   Rita   22      F          81             84             78   Pass
7   8  Kiran   23      M          76             80             77   Pass