In [8]:
import pandas as pd

In [18]:
dirty_data = {
    "student_id": [1, 2, 3, 4, 5, 5, 6, 7, 8],
    "name": ["Ram", "sita", "Gita ", "Hari", "Nita", "Nita", "Aman", "Rita", "Kiran"],
    "age": [21, 22, "twenty", 23, None, None, 24, 22, -1],
    "gender": ["M", "female", "F", "Male", "F", "F", "M", "FEMALE", "M"],
    "math_marks": [78, 85, 69, 90, 74, 74, 88, 81, 76],
    "science_marks": [82, 88, "seventy-two", 91, 79, 79, 87, 84, 80],
    "city": ["Kathmandu", "pokhara ", "Kathmandu", "Lalitpur", "kathmandu", "kathmandu", "Bhaktapur", "Pokhara", "Lalitpur"],
    "enrollment_date": [
        "2023-01-15", "15/01/2023", "2023/01/16",
        None, "2023-01-18", "2023-01-18",
        "2023-01-19", "invalid_date", "2023-01-20"
    ]
}

df = pd.DataFrame(dirty_data)
df

,student_id,name,age,gender,math_marks,science_marks,city,enrollment_date
0,1,Ram,21,M,78,82,Kathmandu,2023-01-15
1,2,sita,22,female,85,88,pokhara,15/01/2023
2,3,Gita,twenty,F,69,seventy-two,Kathmandu,2023/01/16
3,4,Hari,23,Male,90,91,Lalitpur,None
4,5,Nita,None,F,74,79,kathmandu,2023-01-18
5,5,Nita,None,F,74,79,kathmandu,2023-01-18
6,6,Aman,24,M,88,87,Bhaktapur,2023-01-19
7,7,Rita,22,FEMALE,81,84,Pokhara,invalid_date
8,8,Kiran,-1,M,76,80,Lalitpur,2023-01-20

#### Removing irrelevant data

In [19]:
df.drop(columns=["student_id"],inplace=True)
df

    name     age  gender  math_marks science_marks       city enrollment_date
0    Ram      21       M          78            82  Kathmandu      2023-01-15
1   sita      22  female          85            88   pokhara       15/01/2023
2  Gita   twenty       F          69   seventy-two  Kathmandu      2023/01/16
3   Hari      23    Male          90            91   Lalitpur            None
4   Nita    None       F          74            79  kathmandu      2023-01-18
5   Nita    None       F          74            79  kathmandu      2023-01-18
6   Aman      24       M          88            87  Bhaktapur      2023-01-19
7   Rita      22  FEMALE          81            84    Pokhara    invalid_date
8  Kiran      -1       M          76            80   Lalitpur      2023-01-20

#### Checking for null values

In [20]:
df.isnull()

    name    age  gender  math_marks  science_marks   city  enrollment_date
0  False  False   False       False          False  False            False
1  False  False   False       False          False  False            False
2  False  False   False       False          False  False            False
3  False  False   False       False          False  False             True
4  False   True   False       False          False  False            False
5  False   True   False       False          False  False            False
6  False  False   False       False          False  False            False
7  False  False   False       False          False  False            False
8  False  False   False       False          False  False            False

#### Standardizing the text

In [21]:
df['gender'] = df['gender'].str.upper()
df

    name     age  gender  math_marks science_marks       city enrollment_date
0    Ram      21       M          78            82  Kathmandu      2023-01-15
1   sita      22  FEMALE          85            88   pokhara       15/01/2023
2  Gita   twenty       F          69   seventy-two  Kathmandu      2023/01/16
3   Hari      23    MALE          90            91   Lalitpur            None
4   Nita    None       F          74            79  kathmandu      2023-01-18
5   Nita    None       F          74            79  kathmandu      2023-01-18
6   Aman      24       M          88            87  Bhaktapur      2023-01-19
7   Rita      22  FEMALE          81            84    Pokhara    invalid_date
8  Kiran      -1       M          76            80   Lalitpur      2023-01-20

In [22]:
df['gender'] = df['gender'].replace({"MALE":"M",
                                     "FEMALE":"F"})

In [23]:
df

    name     age gender  math_marks science_marks       city enrollment_date
0    Ram      21      M          78            82  Kathmandu      2023-01-15
1   sita      22      F          85            88   pokhara       15/01/2023
2  Gita   twenty      F          69   seventy-two  Kathmandu      2023/01/16
3   Hari      23      M          90            91   Lalitpur            None
4   Nita    None      F          74            79  kathmandu      2023-01-18
5   Nita    None      F          74            79  kathmandu      2023-01-18
6   Aman      24      M          88            87  Bhaktapur      2023-01-19
7   Rita      22      F          81            84    Pokhara    invalid_date
8  Kiran      -1      M          76            80   Lalitpur      2023-01-20

In [25]:
df['name'] = df['name'].str.capitalize()
df['city'] = df['city'].str.capitalize()
df

    name     age gender  math_marks science_marks       city enrollment_date
0    Ram      21      M          78            82  Kathmandu      2023-01-15
1   Sita      22      F          85            88   Pokhara       15/01/2023
2  Gita   twenty      F          69   seventy-two  Kathmandu      2023/01/16
3   Hari      23      M          90            91   Lalitpur            None
4   Nita    None      F          74            79  Kathmandu      2023-01-18
5   Nita    None      F          74            79  Kathmandu      2023-01-18
6   Aman      24      M          88            87  Bhaktapur      2023-01-19
7   Rita      22      F          81            84    Pokhara    invalid_date
8  Kiran      -1      M          76            80   Lalitpur      2023-01-20

#### Removing Duplicates

In [27]:
df = df.drop_duplicates()
df

    name     age gender  math_marks science_marks       city enrollment_date
0    Ram      21      M          78            82  Kathmandu      2023-01-15
1   Sita      22      F          85            88   Pokhara       15/01/2023
2  Gita   twenty      F          69   seventy-two  Kathmandu      2023/01/16
3   Hari      23      M          90            91   Lalitpur            None
4   Nita    None      F          74            79  Kathmandu      2023-01-18
6   Aman      24      M          88            87  Bhaktapur      2023-01-19
7   Rita      22      F          81            84    Pokhara    invalid_date
8  Kiran      -1      M          76            80   Lalitpur      2023-01-20

## **04_data_cleaning.ipynb**

**Goal:** Prepare real-world dirty data.

**You must learn:**

* Detecting missing values:

  * `isnull()`, `notnull()`
* Handling missing values:

  * `dropna()`
  * `fillna()`
* Removing duplicates
* Renaming columns
* Changing data types:

  * `astype()`
* String cleaning:

  * `str.lower()`, `str.strip()`, `str.replace()`
* Basic outlier detection

#### Selecting rows