In [34]:
import pandas as pd
import numpy as np

data = {
    "student_id": [101, 102, 103, 104, 105, 106, 107, 108, 109, 110],
    "name": ["Aarav", "Sita", "Ram", "Gita", "Mohan", "Rina", "Krishna", "Priya", "Sanjay", "Anita"],
    "gender": ["M", "F", "M", "F", "M", "F", "M", "F", "M", "F"],
    "age": [18, 19, 18, 20, 21, 19, 22, 18, 20, 21],
    "math_score": [78, 88, 45, 92, 60, np.nan, 35, 81, 55, 68],
    "science_score": [85, 90, 52, 95, 58, 72, 40, 78, np.nan, 70],
    "english_score": [74, 91, 48, 89, 65, 75, 38, 84, 58, 72],
    "attendance_percent": [92, 96, 70, 98, 80, 85, 60, 90, 75, 88],
    "study_hours_per_week": [12, 15, 6, 18, 8, 10, 4, 14, 7, 9],
    "enrollment_date": pd.to_datetime([
        "2023-01-15", "2023-02-10", "2023-01-20", "2023-03-05",
        "2023-02-18", "2023-01-25", "2023-03-12", "2023-02-01",
        "2023-01-30", "2023-03-20"
    ])
}

df = pd.DataFrame(data)

df

,student_id,name,gender,age,math_score,science_score,english_score,attendance_percent,study_hours_per_week,enrollment_date
0,101,Aarav,M,18,78.0,85.0,74,92,12,2023-01-15
1,102,Sita,F,19,88.0,90.0,91,96,15,2023-02-10
2,103,Ram,M,18,45.0,52.0,48,70,6,2023-01-20
3,104,Gita,F,20,92.0,95.0,89,98,18,2023-03-05
4,105,Mohan,M,21,60.0,58.0,65,80,8,2023-02-18
5,106,Rina,F,19,NaN,72.0,75,85,10,2023-01-25
6,107,Krishna,M,22,35.0,40.0,38,60,4,2023-03-12
7,108,Priya,F,18,81.0,78.0,84,90,14,2023-02-01
8,109,Sanjay,M,20,55.0,NaN,58,75,7,2023-01-30
9,110,Anita,F,21,68.0,70.0,72,88,9,2023-03-20

### Sorting

In [35]:
#sorting in acsending order
df.sort_values("attendance_percent")

,student_id,name,gender,age,math_score,science_score,english_score,attendance_percent,study_hours_per_week,enrollment_date
6,107,Krishna,M,22,35.0,40.0,38,60,4,2023-03-12
2,103,Ram,M,18,45.0,52.0,48,70,6,2023-01-20
8,109,Sanjay,M,20,55.0,NaN,58,75,7,2023-01-30
4,105,Mohan,M,21,60.0,58.0,65,80,8,2023-02-18
5,106,Rina,F,19,NaN,72.0,75,85,10,2023-01-25
9,110,Anita,F,21,68.0,70.0,72,88,9,2023-03-20
7,108,Priya,F,18,81.0,78.0,84,90,14,2023-02-01
0,101,Aarav,M,18,78.0,85.0,74,92,12,2023-01-15
1,102,Sita,F,19,88.0,90.0,91,96,15,2023-02-10
3,104,Gita,F,20,92.0,95.0,89,98,18,2023-03-05

In [36]:
#Sorting in descending order
df.sort_values('age',ascending=False)

,student_id,name,gender,age,math_score,science_score,english_score,attendance_percent,study_hours_per_week,enrollment_date
6,107,Krishna,M,22,35.0,40.0,38,60,4,2023-03-12
4,105,Mohan,M,21,60.0,58.0,65,80,8,2023-02-18
9,110,Anita,F,21,68.0,70.0,72,88,9,2023-03-20
3,104,Gita,F,20,92.0,95.0,89,98,18,2023-03-05
8,109,Sanjay,M,20,55.0,NaN,58,75,7,2023-01-30
1,102,Sita,F,19,88.0,90.0,91,96,15,2023-02-10
5,106,Rina,F,19,NaN,72.0,75,85,10,2023-01-25
0,101,Aarav,M,18,78.0,85.0,74,92,12,2023-01-15
2,103,Ram,M,18,45.0,52.0,48,70,6,2023-01-20
7,108,Priya,F,18,81.0,78.0,84,90,14,2023-02-01

In [37]:
#Sorting based on column
df.sort_index(axis=1)

,age,attendance_percent,english_score,enrollment_date,gender,math_score,name,science_score,student_id,study_hours_per_week
0,18,92,74,2023-01-15,M,78.0,Aarav,85.0,101,12
1,19,96,91,2023-02-10,F,88.0,Sita,90.0,102,15
2,18,70,48,2023-01-20,M,45.0,Ram,52.0,103,6
3,20,98,89,2023-03-05,F,92.0,Gita,95.0,104,18
4,21,80,65,2023-02-18,M,60.0,Mohan,58.0,105,8
5,19,85,75,2023-01-25,F,NaN,Rina,72.0,106,10
6,22,60,38,2023-03-12,M,35.0,Krishna,40.0,107,4
7,18,90,84,2023-02-01,F,81.0,Priya,78.0,108,14
8,20,75,58,2023-01-30,M,55.0,Sanjay,NaN,109,7
9,21,88,72,2023-03-20,F,68.0,Anita,70.0,110,9

In [38]:
df.sort_index(axis=1,ascending=False)

,study_hours_per_week,student_id,science_score,name,math_score,gender,enrollment_date,english_score,attendance_percent,age
0,12,101,85.0,Aarav,78.0,M,2023-01-15,74,92,18
1,15,102,90.0,Sita,88.0,F,2023-02-10,91,96,19
2,6,103,52.0,Ram,45.0,M,2023-01-20,48,70,18
3,18,104,95.0,Gita,92.0,F,2023-03-05,89,98,20
4,8,105,58.0,Mohan,60.0,M,2023-02-18,65,80,21
5,10,106,72.0,Rina,NaN,F,2023-01-25,75,85,19
6,4,107,40.0,Krishna,35.0,M,2023-03-12,38,60,22
7,14,108,78.0,Priya,81.0,F,2023-02-01,84,90,18
8,7,109,NaN,Sanjay,55.0,M,2023-01-30,58,75,20
9,9,110,70.0,Anita,68.0,F,2023-03-20,72,88,21

In [ ]:
#sorting one value as ascending and other as descending
df.sort_values(['science_score','enrollment_date'], ascending=[True,False])

,student_id,name,gender,age,math_score,science_score,english_score,percentage,attendance_percent,study_hours_per_week,enrollment_date,total_score
6,107,Krishna,M,22,35.0,40.0,38,37.67,60,4,2023-03-12,113.0
2,103,Ram,M,18,45.0,52.0,48,48.33,70,6,2023-01-20,145.0
4,105,Mohan,M,21,60.0,58.0,65,61.00,80,8,2023-02-18,183.0
9,110,Anita,F,21,68.0,70.0,72,70.00,88,9,2023-03-20,210.0
5,106,Rina,F,19,NaN,72.0,75,NaN,85,10,2023-01-25,NaN
7,108,Priya,F,18,81.0,78.0,84,81.00,90,14,2023-02-01,243.0
0,101,Aarav,M,18,78.0,85.0,74,79.00,92,12,2023-01-15,237.0
1,102,Sita,F,19,88.0,90.0,91,89.67,96,15,2023-02-10,269.0
3,104,Gita,F,20,92.0,95.0,89,92.00,98,18,2023-03-05,276.0
8,109,Sanjay,M,20,55.0,NaN,58,NaN,75,7,2023-01-30,NaN

### FIltering using conditions

In [39]:
df

,student_id,name,gender,age,math_score,science_score,english_score,attendance_percent,study_hours_per_week,enrollment_date
0,101,Aarav,M,18,78.0,85.0,74,92,12,2023-01-15
1,102,Sita,F,19,88.0,90.0,91,96,15,2023-02-10
2,103,Ram,M,18,45.0,52.0,48,70,6,2023-01-20
3,104,Gita,F,20,92.0,95.0,89,98,18,2023-03-05
4,105,Mohan,M,21,60.0,58.0,65,80,8,2023-02-18
5,106,Rina,F,19,NaN,72.0,75,85,10,2023-01-25
6,107,Krishna,M,22,35.0,40.0,38,60,4,2023-03-12
7,108,Priya,F,18,81.0,78.0,84,90,14,2023-02-01
8,109,Sanjay,M,20,55.0,NaN,58,75,7,2023-01-30
9,110,Anita,F,21,68.0,70.0,72,88,9,2023-03-20

In [40]:
df[(df['age']>=19) & (df["study_hours_per_week"]>=10)]

,student_id,name,gender,age,math_score,science_score,english_score,attendance_percent,study_hours_per_week,enrollment_date
1,102,Sita,F,19,88.0,90.0,91,96,15,2023-02-10
3,104,Gita,F,20,92.0,95.0,89,98,18,2023-03-05
5,106,Rina,F,19,NaN,72.0,75,85,10,2023-01-25

In [41]:
df[df["gender"]=='M']

,student_id,name,gender,age,math_score,science_score,english_score,attendance_percent,study_hours_per_week,enrollment_date
0,101,Aarav,M,18,78.0,85.0,74,92,12,2023-01-15
2,103,Ram,M,18,45.0,52.0,48,70,6,2023-01-20
4,105,Mohan,M,21,60.0,58.0,65,80,8,2023-02-18
6,107,Krishna,M,22,35.0,40.0,38,60,4,2023-03-12
8,109,Sanjay,M,20,55.0,NaN,58,75,7,2023-01-30

In [42]:
df.sort_values("enrollment_date")

,student_id,name,gender,age,math_score,science_score,english_score,attendance_percent,study_hours_per_week,enrollment_date
0,101,Aarav,M,18,78.0,85.0,74,92,12,2023-01-15
2,103,Ram,M,18,45.0,52.0,48,70,6,2023-01-20
5,106,Rina,F,19,NaN,72.0,75,85,10,2023-01-25
8,109,Sanjay,M,20,55.0,NaN,58,75,7,2023-01-30
7,108,Priya,F,18,81.0,78.0,84,90,14,2023-02-01
1,102,Sita,F,19,88.0,90.0,91,96,15,2023-02-10
4,105,Mohan,M,21,60.0,58.0,65,80,8,2023-02-18
3,104,Gita,F,20,92.0,95.0,89,98,18,2023-03-05
6,107,Krishna,M,22,35.0,40.0,38,60,4,2023-03-12
9,110,Anita,F,21,68.0,70.0,72,88,9,2023-03-20

In [43]:
date_sorted = df[(df["enrollment_date"]>="2023-01-30") & (df["enrollment_date"]<"2023-03-10")]
date_sorted.sort_values('enrollment_date')

,student_id,name,gender,age,math_score,science_score,english_score,attendance_percent,study_hours_per_week,enrollment_date
8,109,Sanjay,M,20,55.0,NaN,58,75,7,2023-01-30
7,108,Priya,F,18,81.0,78.0,84,90,14,2023-02-01
1,102,Sita,F,19,88.0,90.0,91,96,15,2023-02-10
4,105,Mohan,M,21,60.0,58.0,65,80,8,2023-02-18
3,104,Gita,F,20,92.0,95.0,89,98,18,2023-03-05

### Creating new columns

In [44]:
df.dropna()

,student_id,name,gender,age,math_score,science_score,english_score,attendance_percent,study_hours_per_week,enrollment_date
0,101,Aarav,M,18,78.0,85.0,74,92,12,2023-01-15
1,102,Sita,F,19,88.0,90.0,91,96,15,2023-02-10
2,103,Ram,M,18,45.0,52.0,48,70,6,2023-01-20
3,104,Gita,F,20,92.0,95.0,89,98,18,2023-03-05
4,105,Mohan,M,21,60.0,58.0,65,80,8,2023-02-18
6,107,Krishna,M,22,35.0,40.0,38,60,4,2023-03-12
7,108,Priya,F,18,81.0,78.0,84,90,14,2023-02-01
9,110,Anita,F,21,68.0,70.0,72,88,9,2023-03-20

In [45]:
df["total_score"] = (df["math_score"] + df["science_score"] + df["english_score"])
df

,student_id,name,gender,age,math_score,science_score,english_score,attendance_percent,study_hours_per_week,enrollment_date,total_score
0,101,Aarav,M,18,78.0,85.0,74,92,12,2023-01-15,237.0
1,102,Sita,F,19,88.0,90.0,91,96,15,2023-02-10,269.0
2,103,Ram,M,18,45.0,52.0,48,70,6,2023-01-20,145.0
3,104,Gita,F,20,92.0,95.0,89,98,18,2023-03-05,276.0
4,105,Mohan,M,21,60.0,58.0,65,80,8,2023-02-18,183.0
5,106,Rina,F,19,NaN,72.0,75,85,10,2023-01-25,NaN
6,107,Krishna,M,22,35.0,40.0,38,60,4,2023-03-12,113.0
7,108,Priya,F,18,81.0,78.0,84,90,14,2023-02-01,243.0
8,109,Sanjay,M,20,55.0,NaN,58,75,7,2023-01-30,NaN
9,110,Anita,F,21,68.0,70.0,72,88,9,2023-03-20,210.0

In [ ]:
#Insering at specified location

df.insert(
    loc=7,
    column="percentage",
    value=((df["total_score"])/3).round(2) #round(2) dispplays only 2 digits after decimal
)

In [47]:
df

,student_id,name,gender,age,math_score,science_score,english_score,percentage,attendance_percent,study_hours_per_week,enrollment_date,total_score
0,101,Aarav,M,18,78.0,85.0,74,79.00,92,12,2023-01-15,237.0
1,102,Sita,F,19,88.0,90.0,91,89.67,96,15,2023-02-10,269.0
2,103,Ram,M,18,45.0,52.0,48,48.33,70,6,2023-01-20,145.0
3,104,Gita,F,20,92.0,95.0,89,92.00,98,18,2023-03-05,276.0
4,105,Mohan,M,21,60.0,58.0,65,61.00,80,8,2023-02-18,183.0
5,106,Rina,F,19,NaN,72.0,75,NaN,85,10,2023-01-25,NaN
6,107,Krishna,M,22,35.0,40.0,38,37.67,60,4,2023-03-12,113.0
7,108,Priya,F,18,81.0,78.0,84,81.00,90,14,2023-02-01,243.0
8,109,Sanjay,M,20,55.0,NaN,58,NaN,75,7,2023-01-30,NaN
9,110,Anita,F,21,68.0,70.0,72,70.00,88,9,2023-03-20,210.0

In [50]:
df["math_science_ratio"] = (df["math_score"]) / (df["science_score"])
df

,student_id,name,gender,age,math_score,science_score,english_score,percentage,attendance_percent,study_hours_per_week,enrollment_date,total_score,math_science_ratio
0,101,Aarav,M,18,78.0,85.0,74,79.00,92,12,2023-01-15,237.0,0.917647
1,102,Sita,F,19,88.0,90.0,91,89.67,96,15,2023-02-10,269.0,0.977778
2,103,Ram,M,18,45.0,52.0,48,48.33,70,6,2023-01-20,145.0,0.865385
3,104,Gita,F,20,92.0,95.0,89,92.00,98,18,2023-03-05,276.0,0.968421
4,105,Mohan,M,21,60.0,58.0,65,61.00,80,8,2023-02-18,183.0,1.034483
5,106,Rina,F,19,NaN,72.0,75,NaN,85,10,2023-01-25,NaN,NaN
6,107,Krishna,M,22,35.0,40.0,38,37.67,60,4,2023-03-12,113.0,0.875000
7,108,Priya,F,18,81.0,78.0,84,81.00,90,14,2023-02-01,243.0,1.038462
8,109,Sanjay,M,20,55.0,NaN,58,NaN,75,7,2023-01-30,NaN,NaN
9,110,Anita,F,21,68.0,70.0,72,70.00,88,9,2023-03-20,210.0,0.971429

### apply() function

In [53]:
new_df = df.dropna()
new_df

,student_id,name,gender,age,math_score,science_score,english_score,percentage,attendance_percent,study_hours_per_week,enrollment_date,total_score,math_science_ratio
0,101,Aarav,M,18,78.0,85.0,74,79.00,92,12,2023-01-15,237.0,0.917647
1,102,Sita,F,19,88.0,90.0,91,89.67,96,15,2023-02-10,269.0,0.977778
2,103,Ram,M,18,45.0,52.0,48,48.33,70,6,2023-01-20,145.0,0.865385
3,104,Gita,F,20,92.0,95.0,89,92.00,98,18,2023-03-05,276.0,0.968421
4,105,Mohan,M,21,60.0,58.0,65,61.00,80,8,2023-02-18,183.0,1.034483
6,107,Krishna,M,22,35.0,40.0,38,37.67,60,4,2023-03-12,113.0,0.875000
7,108,Priya,F,18,81.0,78.0,84,81.00,90,14,2023-02-01,243.0,1.038462
9,110,Anita,F,21,68.0,70.0,72,70.00,88,9,2023-03-20,210.0,0.971429

In [59]:
new_df["name"] = new_df["name"].apply(lambda x:x.upper())
new_df

/tmp/ipykernel_9925/2101121859.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["name"] = new_df["name"].apply(lambda x:x.upper())

,student_id,name,gender,age,math_score,science_score,english_score,percentage,attendance_percent,study_hours_per_week,enrollment_date,total_score,math_science_ratio
0,101,AARAV,M,18,78.0,85.0,74,79.00,92,12,2023-01-15,237.0,0.917647
1,102,SITA,F,19,88.0,90.0,91,89.67,96,15,2023-02-10,269.0,0.977778
2,103,RAM,M,18,45.0,52.0,48,48.33,70,6,2023-01-20,145.0,0.865385
3,104,GITA,F,20,92.0,95.0,89,92.00,98,18,2023-03-05,276.0,0.968421
4,105,MOHAN,M,21,60.0,58.0,65,61.00,80,8,2023-02-18,183.0,1.034483
6,107,KRISHNA,M,22,35.0,40.0,38,37.67,60,4,2023-03-12,113.0,0.875000
7,108,PRIYA,F,18,81.0,78.0,84,81.00,90,14,2023-02-01,243.0,1.038462
9,110,ANITA,F,21,68.0,70.0,72,70.00,88,9,2023-03-20,210.0,0.971429

In [ ]:
##Using apply function with user defined function

def grade(score):
    if score>=80:
        return "A"
    elif score>=60:
        return "B"
    else:
        return "C"
    

new_df["GPA"] = new_df["percentage"].apply(grade)

new_df

/tmp/ipykernel_9925/3331823538.py:10: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["GPA"] = new_df["percentage"].apply(grade)

,student_id,name,gender,age,math_score,science_score,english_score,percentage,attendance_percent,study_hours_per_week,enrollment_date,total_score,math_science_ratio,GPA
0,101,AARAV,M,18,78.0,85.0,74,79.00,92,12,2023-01-15,237.0,0.917647,B
1,102,SITA,F,19,88.0,90.0,91,89.67,96,15,2023-02-10,269.0,0.977778,A
2,103,RAM,M,18,45.0,52.0,48,48.33,70,6,2023-01-20,145.0,0.865385,C
3,104,GITA,F,20,92.0,95.0,89,92.00,98,18,2023-03-05,276.0,0.968421,A
4,105,MOHAN,M,21,60.0,58.0,65,61.00,80,8,2023-02-18,183.0,1.034483,B
6,107,KRISHNA,M,22,35.0,40.0,38,37.67,60,4,2023-03-12,113.0,0.875000,C
7,108,PRIYA,F,18,81.0,78.0,84,81.00,90,14,2023-02-01,243.0,1.038462,A
9,110,ANITA,F,21,68.0,70.0,72,70.00,88,9,2023-03-20,210.0,0.971429,B

### map() function

In [61]:
#maps the gpa
gpa_mapping = {
    "A":"Excellent",
    "B":"Very Good",
    "C":"Good"
}

# maps male as 1 and female as 0
gender_map = {
    "M":"1",
    "F":"0"
}


new_df["gender"] = new_df['gender'].map(gender_map)

#creating new column remarks
new_df['remarks'] = new_df['GPA'].map(gpa_mapping)

new_df

/tmp/ipykernel_9925/2117954530.py:15: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df["gender"] = new_df['gender'].map(gender_map)
/tmp/ipykernel_9925/2117954530.py:18: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  new_df['remarks'] = new_df['GPA'].map(gpa_mapping)

,student_id,name,gender,age,math_score,science_score,english_score,percentage,attendance_percent,study_hours_per_week,enrollment_date,total_score,math_science_ratio,GPA,remarks
0,101,AARAV,1,18,78.0,85.0,74,79.00,92,12,2023-01-15,237.0,0.917647,B,Very Good
1,102,SITA,0,19,88.0,90.0,91,89.67,96,15,2023-02-10,269.0,0.977778,A,Excellent
2,103,RAM,1,18,45.0,52.0,48,48.33,70,6,2023-01-20,145.0,0.865385,C,Good
3,104,GITA,0,20,92.0,95.0,89,92.00,98,18,2023-03-05,276.0,0.968421,A,Excellent
4,105,MOHAN,1,21,60.0,58.0,65,61.00,80,8,2023-02-18,183.0,1.034483,B,Very Good
6,107,KRISHNA,1,22,35.0,40.0,38,37.67,60,4,2023-03-12,113.0,0.875000,C,Good
7,108,PRIYA,0,18,81.0,78.0,84,81.00,90,14,2023-02-01,243.0,1.038462,A,Excellent
9,110,ANITA,0,21,68.0,70.0,72,70.00,88,9,2023-03-20,210.0,0.971429,B,Very Good


### Binning:

  * `pd.cut`
  * `pd.qcut`

In [65]:
d = {'Student': ['Aryan', 'Prajwal', 'Vishakshi', 'Brijkant', 'Kareena'],
        'Marks': [77, 72, 19, 68, 45]}
data = pd.DataFrame(d)
data

     Student  Marks
0      Aryan     77
1    Prajwal     72
2  Vishakshi     19
3   Brijkant     68
4    Kareena     45

In [67]:
bins = [0,50,75,100]
marks_label = ["Low", "Average", "High"]

data['Grade'] = pd.cut(data["Marks"],bins = bins, labels=marks_label,include_lowest=True)

In [68]:
data

     Student  Marks    Grade
0      Aryan     77     High
1    Prajwal     72  Average
2  Vishakshi     19      Low
3   Brijkant     68  Average
4    Kareena     45      Low