In [6]:
import pandas as pd

users = pd.DataFrame({
    "user_id": [1, 2, 3, 4],
    "name": ["Alice", "Bob", "Charlie", "David"],
    "city": ["Kathmandu", "Pokhara", "Lalitpur", "Bhaktapur"]
})

users

   user_id     name       city
0        1    Alice  Kathmandu
1        2      Bob    Pokhara
2        3  Charlie   Lalitpur
3        4    David  Bhaktapur

In [5]:
orders = pd.DataFrame({
    "order_id": [101, 102, 103, 104, 105],
    "user_id": [1, 2, 2, 4, 5],
    "product": ["Rice", "Wheat", "Sugar", "Oil", "Tea"],
    "amount": [500, 300, 200, 450, 100]
})
orders

   order_id  user_id product  amount
0       101        1    Rice     500
1       102        2   Wheat     300
2       103        2   Sugar     200
3       104        4     Oil     450
4       105        5     Tea     100

In [4]:
products = pd.DataFrame({
    "product": ["Rice", "Wheat", "Sugar", "Oil", "Tea", "Coffee"],
    "category": ["Grain", "Grain", "Sweetener", "Oil", "Beverage", "Beverage"],
    "unit_price": [50, 30, 20, 90, 10, 80]
})
products

  product   category  unit_price
0    Rice      Grain          50
1   Wheat      Grain          30
2   Sugar  Sweetener          20
3     Oil        Oil          90
4     Tea   Beverage          10
5  Coffee   Beverage          80

### Inner Join

In [11]:
pd.merge(users,orders,on='user_id',how='inner')

   user_id   name       city  order_id product  amount
0        1  Alice  Kathmandu       101    Rice     500
1        2    Bob    Pokhara       102   Wheat     300
2        2    Bob    Pokhara       103   Sugar     200
3        4  David  Bhaktapur       104     Oil     450

In [14]:
pd.merge(orders,products)

   order_id  user_id product  amount   category  unit_price
0       101        1    Rice     500      Grain          50
1       102        2   Wheat     300      Grain          30
2       103        2   Sugar     200  Sweetener          20
3       104        4     Oil     450        Oil          90
4       105        5     Tea     100   Beverage          10

### Outer/Full Join
- not recommended for ML pipelines

In [8]:
pd.merge(users,orders,how='outer')

   user_id     name       city  order_id product  amount
0        1    Alice  Kathmandu     101.0    Rice   500.0
1        2      Bob    Pokhara     102.0   Wheat   300.0
2        2      Bob    Pokhara     103.0   Sugar   200.0
3        3  Charlie   Lalitpur       NaN     NaN     NaN
4        4    David  Bhaktapur     104.0     Oil   450.0
5        5      NaN        NaN     105.0     Tea   100.0

In [10]:
pd.merge(orders,products,how='outer')

   order_id  user_id product  amount   category  unit_price
0       NaN      NaN  Coffee     NaN   Beverage          80
1     104.0      4.0     Oil   450.0        Oil          90
2     101.0      1.0    Rice   500.0      Grain          50
3     103.0      2.0   Sugar   200.0  Sweetener          20
4     105.0      5.0     Tea   100.0   Beverage          10
5     102.0      2.0   Wheat   300.0      Grain          30

### Left Join
- all rows from left and matching from right

In [17]:
pd.merge(orders,products,on='product',how='left')

   order_id  user_id product  amount   category  unit_price
0       101        1    Rice     500      Grain          50
1       102        2   Wheat     300      Grain          30
2       103        2   Sugar     200  Sweetener          20
3       104        4     Oil     450        Oil          90
4       105        5     Tea     100   Beverage          10

### Right Join
- all rows from right and matching from left

In [18]:
pd.merge(orders,products,on='product',how='right')

   order_id  user_id product  amount   category  unit_price
0     101.0      1.0    Rice   500.0      Grain          50
1     102.0      2.0   Wheat   300.0      Grain          30
2     103.0      2.0   Sugar   200.0  Sweetener          20
3     104.0      4.0     Oil   450.0        Oil          90
4     105.0      5.0     Tea   100.0   Beverage          10
5       NaN      NaN  Coffee     NaN   Beverage          80

## Join
- merges dataframe based on index where the default joining is left join

In [23]:
joined = users.join(products)
joined

   user_id     name       city product   category  unit_price
0        1    Alice  Kathmandu    Rice      Grain          50
1        2      Bob    Pokhara   Wheat      Grain          30
2        3  Charlie   Lalitpur   Sugar  Sweetener          20
3        4    David  Bhaktapur     Oil        Oil          90

### Joining on keys

In [33]:
new = users.join(products,on='user_id')
new

   user_id     name       city product   category  unit_price
0        1    Alice  Kathmandu   Wheat      Grain          30
1        2      Bob    Pokhara   Sugar  Sweetener          20
2        3  Charlie   Lalitpur     Oil        Oil          90
3        4    David  Bhaktapur     Tea   Beverage          10

## Concat
- adds the dataframe vertically by default
- the index doesnt gets changed and remains same as in the original dataframe

In [31]:
conc = pd.concat([users,orders],ignore_index=True)
conc

   user_id     name       city  order_id product  amount
0        1    Alice  Kathmandu       NaN     NaN     NaN
1        2      Bob    Pokhara       NaN     NaN     NaN
2        3  Charlie   Lalitpur       NaN     NaN     NaN
3        4    David  Bhaktapur       NaN     NaN     NaN
4        1      NaN        NaN     101.0    Rice   500.0
5        2      NaN        NaN     102.0   Wheat   300.0
6        2      NaN        NaN     103.0   Sugar   200.0
7        4      NaN        NaN     104.0     Oil   450.0
8        5      NaN        NaN     105.0     Tea   100.0

## **07_merging_and_joining.ipynb**

**Goal:** Combine datasets correctly.

**You must learn:**

* `merge()`:

  * inner
  * left
  * right
  * outer
* Joining on keys vs index
* `join()`
* `concat()` (row-wise & column-wise)
* Handling duplicate columns
* Real-world relational examples

---