In [12]:
import pandas as pd
import numpy as np
from datetime import datetime

#### Creating datetime values

In [13]:
dt_demo = pd.date_range(start="2004-11-10",end="2005-11-10",freq="MS")
dt_demo

DatetimeIndex(['2004-12-01', '2005-01-01', '2005-02-01', '2005-03-01',
               '2005-04-01', '2005-05-01', '2005-06-01', '2005-07-01',
               '2005-08-01', '2005-09-01', '2005-10-01', '2005-11-01'],
              dtype='datetime64[ns]', freq='MS')

In [14]:
dt = pd.date_range(start="2021-10-11",periods=20,freq="MS")
dt

DatetimeIndex(['2021-11-01', '2021-12-01', '2022-01-01', '2022-02-01',
               '2022-03-01', '2022-04-01', '2022-05-01', '2022-06-01',
               '2022-07-01', '2022-08-01', '2022-09-01', '2022-10-01',
               '2022-11-01', '2022-12-01', '2023-01-01', '2023-02-01',
               '2023-03-01', '2023-04-01', '2023-05-01', '2023-06-01'],
              dtype='datetime64[ns]', freq='MS')

In [77]:
data = {
    "date": pd.date_range(start="2023-01-01", end="2023-03-31", freq="D"),
    "temperature": np.random.randint(15, 35, 90),
    "rainfall": np.random.randint(0, 20, 90),
    "humidity": np.random.randint(40, 90, 90),
    "crop_yield": np.random.randint(20, 60, 90)
}

df = pd.DataFrame(data)
df.head()

        date  temperature  rainfall  humidity  crop_yield
0 2023-01-01           18        13        63          27
1 2023-01-02           15        14        77          58
2 2023-01-03           27         6        67          59
3 2023-01-04           31        11        73          22
4 2023-01-05           20        16        65          40

In [78]:
df['date'][0]

Timestamp('2023-01-01 00:00:00')

#### Converting to datetime

In [79]:
df['date']=pd.to_datetime(df['date'])
df.dtypes

date           datetime64[ns]
temperature             int64
rainfall                int64
humidity                int64
crop_yield              int64
dtype: object

In [80]:
df = df.set_index('date')
df

            temperature  rainfall  humidity  crop_yield
date
2023-01-01           18        13        63          27
2023-01-02           15        14        77          58
2023-01-03           27         6        67          59
2023-01-04           31        11        73          22
2023-01-05           20        16        65          40
...                 ...       ...       ...         ...
2023-03-27           23         2        50          52
2023-03-28           21         1        47          33
2023-03-29           21        15        87          34
2023-03-30           18        14        41          43
2023-03-31           27         1        48          41

[90 rows x 4 columns]

In [81]:
df.reset_index(inplace=True)

In [82]:
df

         date  temperature  rainfall  humidity  crop_yield
0  2023-01-01           18        13        63          27
1  2023-01-02           15        14        77          58
2  2023-01-03           27         6        67          59
3  2023-01-04           31        11        73          22
4  2023-01-05           20        16        65          40
..        ...          ...       ...       ...         ...
85 2023-03-27           23         2        50          52
86 2023-03-28           21         1        47          33
87 2023-03-29           21        15        87          34
88 2023-03-30           18        14        41          43
89 2023-03-31           27         1        48          41

[90 rows x 5 columns]

In [83]:
df['date'] = pd.to_datetime(df['date'])

In [84]:
df.dtypes

date           datetime64[ns]
temperature             int64
rainfall                int64
humidity                int64
crop_yield              int64
dtype: object

#### Resampling

In [85]:
df = df.set_index('date').resample('M').mean()
df

/tmp/ipykernel_19696/3572297704.py:1: FutureWarning: 'M' is deprecated and will be removed in a future version, please use 'ME' instead.
  df = df.set_index('date').resample('M').mean()

            temperature   rainfall   humidity  crop_yield
date
2023-01-31    25.032258  10.354839  65.225806   40.935484
2023-02-28    24.785714   8.107143  64.428571   40.750000
2023-03-31    22.870968   8.032258  56.967742   41.225806

In [108]:
data = {
    "date": pd.date_range(start="2023-01-01", end="2023-03-31", freq="D"),
    "temperature": np.random.randint(15, 35, 90),
    "rainfall": np.random.randint(0, 20, 90),
    "humidity": np.random.randint(40, 90, 90),
    "crop_yield": np.random.randint(20, 60, 90)
}

df1 = pd.DataFrame(data)
df1

         date  temperature  rainfall  humidity  crop_yield
0  2023-01-01           23         6        57          27
1  2023-01-02           25        14        85          20
2  2023-01-03           19         5        84          42
3  2023-01-04           29         9        50          40
4  2023-01-05           22        16        61          42
..        ...          ...       ...       ...         ...
85 2023-03-27           18         7        47          48
86 2023-03-28           25         7        49          41
87 2023-03-29           20        13        44          46
88 2023-03-30           20         8        60          56
89 2023-03-31           15        15        60          58

[90 rows x 5 columns]

In [109]:
df1['date']= pd.to_datetime(df1['date'])
df1.dtypes

date           datetime64[ns]
temperature             int64
rainfall                int64
humidity                int64
crop_yield              int64
dtype: object

In [112]:
df1["2023-01-01":"2023-01-10"]

            temperature  rainfall  humidity  crop_yield
date
2023-01-01           23         6        57          27
2023-01-02           25        14        85          20
2023-01-03           19         5        84          42
2023-01-04           29         9        50          40
2023-01-05           22        16        61          42
2023-01-06           28        17        60          26
2023-01-07           25         8        84          42
2023-01-08           30        10        88          52
2023-01-09           24        14        81          20
2023-01-10           24        13        88          46

In [114]:
df1['3days_temp_avg'] = df1['temperature'].rolling(window=3).mean()
df1

            temperature  rainfall  humidity  crop_yield  3days_temp_avg
date
2023-01-01           23         6        57          27             NaN
2023-01-02           25        14        85          20             NaN
2023-01-03           19         5        84          42       22.333333
2023-01-04           29         9        50          40       24.333333
2023-01-05           22        16        61          42       23.333333
...                 ...       ...       ...         ...             ...
2023-03-27           18         7        47          48       21.666667
2023-03-28           25         7        49          41       21.666667
2023-03-29           20        13        44          46       21.000000
2023-03-30           20         8        60          56       21.666667
2023-03-31           15        15        60          58       18.333333

[90 rows x 5 columns]

### Shifting
- moving data forward or backward along the time axis
- shift(1) -> moves down -> uses past values
- shift(-1) -. modes up -> uses future values

#### Positive Shifting

In [115]:
df1['temp_shift1'] = df1["temperature"].shift(1)
df1

,temperature,rainfall,humidity,crop_yield,3days_temp_avg,temp_shift1
date,,,,,,
2023-01-01,23,6,57,27,NaN,NaN
2023-01-02,25,14,85,20,NaN,23.0
2023-01-03,19,5,84,42,22.333333,25.0
2023-01-04,29,9,50,40,24.333333,19.0
2023-01-05,22,16,61,42,23.333333,29.0
...,...,...,...,...,...,...
2023-03-27,18,7,47,48,21.666667,22.0
2023-03-28,25,7,49,41,21.666667,18.0
2023-03-29,20,13,44,46,21.000000,25.0
2023-03-30,20,8,60,56,21.666667,20.0
2023-03-31,15,15,60,58,18.333333,20.0

#### Negative Shifting

In [116]:
df1['temp_shift_2'] = df1['temperature'].shift(-2)
df1

,temperature,rainfall,humidity,crop_yield,3days_temp_avg,temp_shift1,temp_shift_2
date,,,,,,,
2023-01-01,23,6,57,27,NaN,NaN,19.0
2023-01-02,25,14,85,20,NaN,23.0,29.0
2023-01-03,19,5,84,42,22.333333,25.0,22.0
2023-01-04,29,9,50,40,24.333333,19.0,28.0
2023-01-05,22,16,61,42,23.333333,29.0,25.0
...,...,...,...,...,...,...,...
2023-03-27,18,7,47,48,21.666667,22.0,20.0
2023-03-28,25,7,49,41,21.666667,18.0,20.0
2023-03-29,20,13,44,46,21.000000,25.0,15.0
2023-03-30,20,8,60,56,21.666667,20.0,NaN
2023-03-31,15,15,60,58,18.333333,20.0,NaN